function hashSlug(slug: string): number {
  const s = slug || "agent";
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h;
}

/** Deterministic hue (0–359°) for an agent slug. */
export function agentHueRotation(slug: string): number {
  return hashSlug(slug) % 360;
}

/**
 * Deterministic flame avatar from slug: a data-URI SVG of a stylized flame
 * (Lucide Flame path), tinted with a per-slug hue so each agent looks distinct.
 */
export function identiconUrl(slug: string): string {
  const hue = agentHueRotation(slug);
  const fill = `hsl(${hue}, 90%, 58%)`;
  const stroke = `hsl(${hue}, 95%, 35%)`;
  const bg = `hsl(${hue}, 70%, 12%)`;
  // Lucide "flame" icon path centered in a 24-unit viewBox.
  const path = "M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z";
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="12" fill="${bg}"/><path d="${path}" fill="${fill}" stroke="${stroke}" stroke-width="0.8" stroke-linejoin="round"/></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

/**
 * Returns true for URLs that were generated by an earlier auto-avatar scheme
 * (DiceBear identicons, or previous data-URI variants we want to override).
 * We treat these as "not a user-uploaded avatar" so the flame regenerates.
 */
function isAutoGeneratedAvatar(url: string): boolean {
  if (!url) return false;
  if (url.includes("api.dicebear.com")) return true;
  if (url.startsWith("data:image/svg+xml")) return true;
  return false;
}

/** True when the URL looks like a real user-uploaded image (not auto-generated). */
export function isUserUploadedAvatar(url: string | null | undefined): url is string {
  if (!url) return false;
  if (url.startsWith("#")) return false;
  return !isAutoGeneratedAvatar(url);
}

/** Prefer stored avatar (only if user-uploaded); otherwise the slug flame. */
export function agentAvatarDisplayUrl(agent: { slug: string; avatarUrl: string | null }): string {
  if (agent.avatarUrl && !isAutoGeneratedAvatar(agent.avatarUrl)) return agent.avatarUrl;
  return identiconUrl(agent.slug);
}

/**
 * DM sessions store `agentAvatar` as an image URL or a legacy hex color.
 * Normalize to an image URL using the slug flame when needed.
 */
export function dmSessionAvatarImageUrl(
  agentAvatar: string | null,
  agentSlug: string,
): string {
  if (agentAvatar && !agentAvatar.startsWith("#") && !isAutoGeneratedAvatar(agentAvatar)) {
    return agentAvatar;
  }
  return identiconUrl(agentSlug);
}

/**
 * Workspace `Agent` may still use hex `avatar` (demo bots) or an image URL from the API.
 * Always return an image URL — flame seeded by slug or id.
 */
export function appAgentAvatarSrc(agent: {
  avatar?: string;
  slug?: string;
  id: string;
}): string {
  const a = agent.avatar?.trim();
  if (a && !a.startsWith("#") && !isAutoGeneratedAvatar(a)) return a;
  return identiconUrl(agent.slug || agent.id);
}
